### ISSUE TITLE
The tooltip around the button will show again when closing the modal

### ISSUE THREAD

**Issue by cheton** [cheton/styled-ui#345]
### Description

The button will receive focus when closing the modal. It should provide the ability to turn off the `onFocus` event for the tooltip.

### How to reproduce

```jsx
<Tooltip label="This is a tooltip.">
  <Button onClick={onOpen}>
    Launch modal
  </Button>
</Tooltip>
```

#### 1. Hover over the button
![image](https://user-images.githubusercontent.com/447801/133202278-24c25546-98e9-4196-87f5-f28a22e3a1f2.png)

#### 2. Launch the modal
![image](https://user-images.githubusercontent.com/447801/133202312-00b8fa05-6829-4a76-948b-827bb4801a87.png)

#### 3. Close the modal
![image](https://user-images.githubusercontent.com/447801/133202345-73f51125-170a-4886-9d7a-cf4218032316.png)

**Comment by gckenny** [comment]
Here have a workaround is add finalFocusRef prop into <Modal>.

**Comment by cheton** [comment]
@gckenny PR #748 introduces several new props to Drawer, Modal, and Tooltip components, enabling more precise control for the focus behavior.
