### ISSUE TITLE
The isControlled status in CheckboxGroup component is wrong when async fetching CheckboxGroup's value

### ISSUE THREAD

**Issue by frank3en** [cheton/styled-ui#346]
## Description

The isControlled status in CheckboxGroup component is wrong when async fetching CheckboxGroup's value.

## Demo

[https://codesandbox.io/s/tonic-checkboxgroup-sample-7625l](https://codesandbox.io/s/tonic-checkboxgroup-sample-7625l)

## Problem 

```javascript
// styled-ui/packages/react-styled-ui/src/CheckboxGroup/index.js
// line 16
 const { current: isControlled } = useRef(valueProp != null);
```
I think the usage of double equal in `valueProp != null` is the reason.

**Comment by cheton** [comment]
Hi @frank3hen 

Thank you for reporting this issue. We've looked into it for switching a value from uncontrolled to be controlled. 

The problem may exist in the following components:

* [x] Accordion (in progress)
    - #352 
* [x] Menu
* [x] Popover
* [x] Tabs
* [x] Tooltip
* [x] CheckboxGroup (merged in 0.19.0)
    - #350
* [x] RadioGroup (merged in 0.19.0)
    - #351

I will make several PRs to fix these bugs. Please stay tune for further updates.

**Comment by cheton** [comment]
@frank3hen 

A recommended fix to your app is always to provide a default value to each key of the state, like so:

```js
const [data, setData] = useState({ favFruits: [] });
```

**Comment by cheton** [comment]
Both `CheckboxGroup` and `RadioGroup` were updated in [0.19.0](https://github.com/trendmicro-frontend/styled-ui/releases/tag/%40trendmicro%2Freact-styled-ui%400.19.0)
