### ISSUE TITLE
Menu dropdown Component throwing errors when clicking into before page loads.

### ISSUE THREAD

**Issue by brou0071** [cheton/styled-ui#355]
https://user-images.githubusercontent.com/6666761/137517972-050eb4d3-99db-4c46-b718-73340152eaeb.mov

**Comment by cheton** [comment]
Hi @brou0071 

Would you be able to reproduce this issue by adding a simplified example on CodesandBox?

Here is a CodesandBox example:
https://codesandbox.io/s/tonic-checkboxgroup-sample-7625l

**Comment by cheton** [comment]
It will be fixed in PR #383

**Comment by cheton** [comment]
Fixed in PR #383 and v0.21.1
