### ISSUE TITLE
Why not support separate disable prop for the vertical and horizontal scrollbar

### ISSUE THREAD

**Issue by TrendAlan** [cheton/styled-ui#377]
From this code: https://github.com/trendmicro-frontend/tonic-ui/blob/master/packages/react/src/Scrollbar/Scrollbar.js#L47-L48

We can see that the horizontal and vertical scrollbars both ref the same prop disabled.
But if I only want to disable the vertical scrollbar and keep the horizontal one.
What should I do?

**Comment by cheton** [comment]
Hi @TrendAlan 
Please help review PR #380 for the new change. Thank you 🙏
