### ISSUE TITLE
tooltip issue

### ISSUE THREAD

**Issue by 551061ff** [cheton/styled-ui#396]
tooltip can not show correctly when set defaultIsOpen true.
![image](https://user-images.githubusercontent.com/40588553/144348674-eea76859-76f1-46bd-8671-9b4bf4671374.png)

**Comment by cheton** [comment]
@551061ff 
Thank you for reporting this issue. It appears that both `Popover` and `Tooltip` components cannot work properly with the `isOpen` prop.

I will put it in the backlog.

**Comment by 551061ff** [comment]
@cheton Thanks for reply! I also found some issue about this, I will give a mini repo after check for it.

**Comment by cheton** [comment]
Hi @551061ff 

I will create PRs to fix the issue that cannot locate the popover/tooltip trigger if explicitly set the `isOpen` prop.

* Tooltip: https://github.com/trendmicro-frontend/tonic-ui/pull/408
* Popover: https://github.com/trendmicro-frontend/tonic-ui/pull/410

**Comment by cheton** [comment]
fixed in [0.24.0](https://github.com/trendmicro-frontend/tonic-ui/releases/tag/%40trendmicro%2Freact-styled-ui%400.24.0)
