### ISSUE TITLE
Some issues on PR 432 build

### ISSUE THREAD

**Issue by tinaClin** [cheton/styled-ui#448]
https://trendmicro-frontend.github.io/tonic-ui-demo/react/pr-432/getting-started/usage

- [x] [Usage page](https://trendmicro-frontend.github.io/tonic-ui-demo/react/pr-432/getting-started/usage)的`demo page`連結 404 → fixed, review in https://trendmicro-frontend.github.io/tonic-ui-demo/react/pr-444/getting-started/usage
![image](https://user-images.githubusercontent.com/24446505/148013223-69fec095-3fd9-48e2-8b20-00981117bf3b.png)

- [x] [Versions page](https://trendmicro-frontend.github.io/tonic-ui-demo/react/pr-432/getting-started/versions)中header的`Documentation`和`Release notes`連結 404
![image](https://user-images.githubusercontent.com/24446505/148013311-6275ad5f-b9a8-4456-8599-4409c96f82f6.png)

- [x] [Contributing page](https://trendmicro-frontend.github.io/tonic-ui-demo/react/pr-432/getting-started/contributing)的document路徑要改成 ~~packages/docs~~ → `packages/react-docs`
![image](https://user-images.githubusercontent.com/24446505/148013546-57d36b7c-26cb-47bb-ae99-88d49ccab521.png)

- [x] [Color Style page](https://trendmicro-frontend.github.io/tonic-ui-demo/react/pr-432/system/color-style)建議把序號(?)拿掉。
![image](https://user-images.githubusercontent.com/24446505/148013885-c45eb893-db08-4b02-8410-8cf9f0c417d9.png)

- [X] [Badge](https://trendmicro-frontend.github.io/tonic-ui-demo/react/pr-432/components/badge): `colors`連結404  → fixed, review in https://trendmicro-frontend.github.io/tonic-ui-demo/react/pr-444/components/badge
![image](https://user-images.githubusercontent.com/24446505/148013964-ec034308-d4f2-46ac-8af1-14d3dc2ba410.png)

- [X] [Tooltip](https://trendmicro-frontend.github.io/tonic-ui-demo/react/pr-432/components/tooltip): `Tooltip with Menu` example畫面跑版 → fixed, review in https://trendmicro-frontend.github.io/tonic-ui-demo/react/pr-444/components/tooltip
![image](https://user-images.githubusercontent.com/24446505/148014336-e9423449-0f50-4271-8fd3-696fdc2a44c6.png)

- [X] [Alert](https://trendmicro-frontend.github.io/tonic-ui-demo/react/pr-432/components/alert): `Transition effects` example無作用。 → fixed, review in https://trendmicro-frontend.github.io/tonic-ui-demo/react/pr-444/components/alert
![image](https://user-images.githubusercontent.com/24446505/148014610-672ec94f-8776-4e3e-b7e7-889a821808ff.png)

- [x] [Switch](https://trendmicro-frontend.github.io/tonic-ui-demo/react/pr-432/components/switch): `Checkbox`連結404
![image](https://user-images.githubusercontent.com/24446505/148014684-7e7412f8-09c6-4424-aec8-bdae23e7aac2.png)

- [X] [Box](https://trendmicro-frontend.github.io/tonic-ui-demo/react/pr-432/components/box): 動畫盒有一面空白。 → fixed, review in https://trendmicro-frontend.github.io/tonic-ui-demo/react/pr-444/components/box
![image](https://user-images.githubusercontent.com/24446505/148014834-1b9bbba8-8217-42b2-86c8-6d7ece42e2aa.png)

- [x] [Tabs](https://trendmicro-frontend.github.io/tonic-ui-demo/react/pr-432/components/tabs): `Change the tabs alignment`範例中，Tabs沒有靠右。
![Screenshot2022_01_04_134753](https://user-images.githubusercontent.com/24446505/148015040-7d598bfe-2954-455b-9831-79043f0d33b2.jpg)

- [x] 單行的import範例，`COPY`按鈕掉下來了。
![image](https://user-images.githubusercontent.com/24446505/148015193-de002d1b-5c1b-4581-a58d-355678be6e95.png)

**Comment by cheton** [comment]
fixed in PR #444
