### ISSUE TITLE
Close button on tag is not visible in light mode

### ISSUE THREAD

**Issue by trend-derek-hawker** [cheton/styled-ui#489]
The close button on Tag is not visible on light mode when variant="outline". Probably something to consider when working on https://github.com/trendmicro-frontend/tonic-ui/issues/486

https://trendmicro-frontend.github.io/tonic-ui/react/latest/components/tag

**Light Mode**

![image](https://user-images.githubusercontent.com/79874774/152869929-a04f4bf2-f840-443d-91ce-c422a9c10bc7.png)

**Dark mode for comparison** 

![image](https://user-images.githubusercontent.com/79874774/152869640-3de9fd4c-5cb6-4f0b-911a-d779358b34a9.png)

**Comment by cheton** [comment]
The color issue in light mode will be fixed with #486

**Comment by cheton** [comment]
Published [v1.0.0-beta](https://www.npmjs.com/package/@tonic-ui/react/v/1.0.0-beta)
