### ISSUE TITLE
Unexpected modal position change

### ISSUE THREAD

**Issue by light049** [cheton/styled-ui#504]
**Affected browser:**
Chrome, Edge

**Reproduce steps:**
1. Make a simple modal
2. Set long contents in modal to have scrolling, put radios at bottom
```
...
          <ModalBody>
            <Box>
              <Box h={800}/>
              <RadioGroup variantColor="green" defaultValue="1">
                <Stack direction="row" spacing="3x">
                  <Radio value="1">Radio 1</Radio>
                  <Radio value="2">Radio 2</Radio>
                </Stack>
              </RadioGroup>
            </Box>
          </ModalBody>
...
```
3. Open the modal, scroll to bottom
<kbd><img src=https://user-images.githubusercontent.com/1054905/157351189-4387eb7c-a07d-46a3-a9fb-f122083150e8.png></kbd>
4. Click to change radio select
6. The modal have unexpected position change
<kbd><img src=https://user-images.githubusercontent.com/1054905/157351442-ed2f1bf6-8fb6-44c8-8839-f163b8d913f3.png></kbd>

**Expected results:**
The modal should keep the same position

**Comment by light049** [comment]
As a reference, it seems removing the style 'overflow: hidden' would make this weird behavior disappear.
<kbd><img src="https://user-images.githubusercontent.com/1054905/157362904-c383d1de-b781-4986-8875-9201270e7cb3.png"></kbd>
<kbd><img src=https://user-images.githubusercontent.com/1054905/157363207-4a90e5dd-d9b6-4710-82fe-c975e1289e1b.png></kbd>

**Comment by cheton** [comment]
Related to https://github.com/trendmicro-frontend/tonic-ui/issues/344

**Comment by cheton** [comment]
@light049 We will provide a hot fix to both `master` and `v0` branches.

**Comment by light049** [comment]
> Related to #344

Thx, hope the style 'overflow:hidden' could be the clue to fix this issue.

**Comment by cheton** [comment]
Merged to `v0` and `master` branches
