### ISSUE TITLE
bug: modal with `outside` scroll behavior is not able to scroll the full modal on the viewport when the content changes

### ISSUE THREAD

**Issue by light049** [cheton/styled-ui#522]
### Issue
The modal could not scroll to top of modal in specific condition.

### Reproduce steps
1. Set a simple modal with tabs that have different content height
```
...
      <Modal
        ...
        scrollBehavior='outside'
      >
        <ModalOverlay />
        <ModalContent>
          <ModalHeader>
            Modal Title
          </ModalHeader>
          <ModalBody>
            <Tabs>
              <TabList>
                <Tab>tab 1</Tab>
                <Tab>tab 2</Tab>
              </TabList>
              <TabPanels>
                <TabPanel>
                  <Lorem count={2} />
                </TabPanel>
                <TabPanel>
                  <Lorem count={20} />
                </TabPanel>
              </TabPanels>
            </Tabs>
          <ModalBody>
...
```
2. Show the modal
<kbd><img src=https://user-images.githubusercontent.com/1054905/158719379-18a9309a-7c20-4b16-ae0a-8a39e3ce30cd.png></kbd> 
3. Switch to 'tab 2'
<kbd><img src=https://user-images.githubusercontent.com/1054905/158719482-3356abe6-269e-422f-a499-82087ac6ac74.png></kbd>
4. Scrolling to bottom would be fine, but the top of modal would not be reachable
<kbd><img src=https://user-images.githubusercontent.com/1054905/158720256-0b82ddab-cb27-4bbc-86a6-a8996d469585.png></kbd>
<kbd><img src=https://user-images.githubusercontent.com/1054905/158720643-439fb99d-97f7-40e0-be64-e67d515a8d26.png></kbd>

### Note
After resizing browser window, the modal position would changed and able to scroll to view the full modal
<kbd><img src=https://user-images.githubusercontent.com/1054905/158721126-18c171af-0b40-461d-9bd7-fd54db382831.png></kbd>

### Expect results
Able to scroll to view the top part of modal.

**Comment by cheton** [comment]
It seems the modal container should also observe the event when the modal content's size was changed.

https://github.com/trendmicro-frontend/tonic-ui/blob/%40tonic-ui/react%401.0.0-beta.0/packages/react/src/modal/ModalContainer.js#L68-L72

```js
  viewport?.addEventListener?.('resize', updateVerticalAlignment);

    return () => {
      viewport?.removeEventListener?.('resize', updateVerticalAlignment);
    };
```

I will fix it using `ResizeObserver` (or other approaches) in PR #520
