### ISSUE TITLE
[Issue] The popover would not disappear when wrapping disabled button

### ISSUE THREAD

**Issue by light049** [cheton/styled-ui#550]
## Descriptions
The popover would not disappear as expected when wrapping a disabled button.

<kbd><img src=https://user-images.githubusercontent.com/1054905/160764570-ae68811d-9502-4de8-ba3f-5c020c7e1396.png></kbd>

## Workaround
As a reference to get expected results
<kbd><img src=https://user-images.githubusercontent.com/1054905/160769559-86074044-584e-4dcb-8297-05a7d16ece78.png></kbd>

**Comment by cheton** [comment]
@light049 
Related to https://github.com/facebook/react/issues/18753

Pointer Events should have been supported by modern browsers and React v16.4
* https://caniuse.com/?search=onpointerenter
* https://caniuse.com/?search=onpointerleave
* https://caniuse.com/?search=onpointermove
* https://reactjs.org/blog/2018/05/23/react-v-16-4.html#pointer-events

**Comment by cheton** [comment]
@light049 This issue will be resolved in PR #551

You can use the follwoing code as a temporary workaround while waiting for a hotfix release.

```jsx
<Popover trigger="hover">
  <PopoverTrigger>
    {({ getPopoverTriggerProps }) => {
      const popoverTriggerProps = getPopoverTriggerProps();
      popoverTriggerProps.onPointerEnter = popoverTriggerProps.onMouseEnter;
      popoverTriggerProps.onPointerLeave = popoverTriggerProps.onMouseLeave;
      popoverTriggerProps.onPointerMove = popoverTriggerProps.onMouseMove;
      return ( 
        <Button disabled {...popoverTriggerProps}>Disabled Button</Button>
      );
    }}
  </PopoverTrigger>
  <PopoverContent>
    Popover
  </PopoverContent>
</Popover>
```

**Comment by light049** [comment]
@cheton Thanks for your example.
I meet another weird condition if I abstract the button component out to be another component.
The popover content would not localed at expected position.

<kbd><img src=https://user-images.githubusercontent.com/1054905/160793505-90e0fb5a-40ff-4789-887a-2505daed2d6c.png></kbd>

```
const Btn = ({
  disabled,
  ...restProps
}) => {
  return ( 
    <Button disabled {...restProps}>Disabled Button</Button>
  );
};

const Example = () => {
  return (
    <Popover trigger="hover">
      <PopoverTrigger>
        {({ getPopoverTriggerProps }) => {
          const popoverTriggerProps = getPopoverTriggerProps();
          popoverTriggerProps.onPointerEnter = popoverTriggerProps.onMouseEnter;
          popoverTriggerProps.onPointerLeave = popoverTriggerProps.onMouseLeave;
          popoverTriggerProps.onPointerMove = popoverTriggerProps.onMouseMove;
          return ( 
            <Btn disabled {...popoverTriggerProps} />
          );
        }}
      </PopoverTrigger>
      <PopoverContent>
        Popover
      </PopoverContent>
    </Popover>  
  );
}
```

**Comment by cheton** [comment]
You have to wrap your component using `forwardRef`:

```jsx
const Btn = forwardRef((
  {
    disabled,
    ...restProps
  },
  ref,
) => {
  return ( 
    <Button ref={ref} disabled {...restProps}>Disabled Button</Button>
  );
});
```

**Comment by atomiks** [comment]
FYI pointer events (in the nature of fixing this bug, not the support in general) don't work in Safari also so I wouldn't consider it a solution. It's a problem with React's delegation/synthetic system: https://twitter.com/atomiksdev/status/1510512851198242819

**Comment by cheton** [comment]
@atomiks @light049 This issue is related to https://github.com/facebook/react/issues/11972

See https://github.com/chakra-ui/chakra-ui/blob/next/packages/tooltip/src/use-tooltip.ts

```js
  /**
   * This allows for catching mouseleave events when the tooltip
   * trigger is disabled. There's currently a known issue in
   * React regarding the onMouseLeave polyfill.
   * @see https://github.com/facebook/react/issues/11972
   */
  useEventListener("mouseleave", closeWithDelay, () => ref.current)
```

The workaround is to listen to the native `mouseleave` event to mitigate the known issue.

**Comment by cheton** [comment]
Fixed in https://github.com/trendmicro-frontend/tonic-ui/pull/561
