### ISSUE TITLE
[Issue] The state updating in Popover has chance to run after unmount and results warning

### ISSUE THREAD

**Issue by light049** [cheton/styled-ui#553]
## Descriptions
The state update in Popover might consider the mounting status.

## Reproduce Steps
Sample on codesandbox: https://8hmk3u.csb.app/
1. Open the select and mouse over the 2nd menu item to show tooltip
<kbd><img src=https://user-images.githubusercontent.com/1054905/161803910-da846f64-08d6-4e96-8a95-49da1da70326.png></kbd>
2. Clicking the menu item after toolip show
<kbd><img src=https://user-images.githubusercontent.com/1054905/161804047-09d2cfcc-7587-499a-9def-fcfe6a307426.png></kbd>
3. Warning appears
<kbd><img src=https://user-images.githubusercontent.com/1054905/161804146-55f9e244-ddcf-4625-aeda-3531a1a00c69.png></kbd>

**Comment by tinaClin** [comment]
### Root cause
exec `onExited` event after the component unmounted

https://github.com/trendmicro-frontend/tonic-ui/blob/master/packages/react/src/menu/MenuList.js#L127
![image](https://user-images.githubusercontent.com/24446505/162376732-c9513bd5-19f7-41be-870f-017b2f85c680.png)

**Comment by light049** [comment]
> ### Root cause
> exec `onExited` event after the component unmounted
> 
> https://github.com/trendmicro-frontend/tonic-ui/blob/master/packages/react/src/menu/MenuList.js#L127 ![image](https://user-images.githubusercontent.com/24446505/162376732-c9513bd5-19f7-41be-870f-017b2f85c680.png)

Curious about if this has relation with the prop 'unmountOnExit' setting true here (default is false)
<kbd><img src=https://user-images.githubusercontent.com/1054905/162529479-e8d51533-9b05-480a-86d4-b454ece98bd3.png></kbd>

**Comment by cheton** [comment]
The issue will no longer happren in the latest version of the Tonic UI:
https://codesandbox.io/s/tonic-ui-ellipsistooltip-in-menu-forked-kxebe4
