### ISSUE TITLE
Switch Fill Not Synced with colorMode

### ISSUE THREAD

**Issue by GeorgianaAI** [cheton/styled-ui#596]
Looks like there is a **fill** for the **switch** that appears as a **black** border regardless of the theme (dark or light) when the user clicks on the switch. The fill is set to "black" below:
https://github.com/trendmicro-frontend/tonic-ui/blob/master/packages/react/src/switch/styles.js#L56

Tonic website:
<img width="991" alt="Screen Shot 2022-06-09 at 2 56 03 PM" src="https://user-images.githubusercontent.com/66571565/172929663-3567c658-346b-4866-bcec-e5cb8c4a00d0.png">

<img width="752" alt="Screen Shot 2022-06-09 at 2 56 12 PM" src="https://user-images.githubusercontent.com/66571565/172929680-91ac7bf1-c56f-42eb-a7d6-32c8073710f8.png">

Our UI:
![Screen Shot 2022-06-09 at 2 51 12 PM](https://user-images.githubusercontent.com/66571565/172929477-0df5b270-b511-4619-ab6e-6cf1d39a6ad4.png)

![Screen Shot 2022-06-09 at 2 51 40 PM](https://user-images.githubusercontent.com/66571565/172929501-1bb1e433-a2b1-4e50-8d10-95226aa97eaa.png)

**Comment by cheton** [comment]
Hi @GeorgiDS9 

I just checked the Tonic UI visual spec in Figma, the inner border color should be `white` in the light mode. We will create a patch release to fix this issue. Thank you for reporting that to us.

https://www.figma.com/file/62S1DnH4Pqy1MxJQCcLXUA/Tonic---Light-Mode?node-id=458%3A1
![image](https://user-images.githubusercontent.com/447801/173013952-6c900ce2-9d22-479f-a791-c63567154b5b.png)

https://www.figma.com/file/bHr2zAshr0D5ROp8vCVPFR/Tonic---Dark-Mode?node-id=110%3A0
![image](https://user-images.githubusercontent.com/447801/173013921-a71124c4-1bb2-470b-b8f3-05517f74e953.png)

**Comment by cheton** [comment]
@GeorgiDS9

It's resolved in [@tonic-ui/react@1.2.7](https://github.com/trendmicro-frontend/tonic-ui/releases/tag/%40tonic-ui%2Freact%401.2.7)

**Comment by GeorgianaAI** [comment]
Thank you, Cheton! I appreciate the quick turnaround.

P.S. I am a FE developer with the Narnia Team, btw. Thanks for including me.
