### ISSUE TITLE
Disabled UI for SearchInput feels incomplete

### ISSUE THREAD

**Issue by derekhawker** [cheton/styled-ui#616]
Hi, I was trying out the disabled prop on SearchInput, but found some behaviour unexpected. Maybe it's just me, though, so I thought I would try asking.

Screenshot below of a SearchInput without disabled (top) and with disabled (bottom) 
<img width="1522" alt="image" src="https://user-images.githubusercontent.com/1403641/189419305-cf632e9c-0f42-44a6-9464-135b81a85431.png">

There were two surprises for me: 
1. The clear input button is clickable while disabled, allowing the input to be cleared. I feel like it should have similar disabled styling as other icon buttons (opacity, mouse cursor changes to not allowed) and shouldn't be clickable
2. I expected the search icon on the left to share the same disabled styling (opacity) as the rest of the input.

The code I used in screenshot:
```
<Stack direction="column" spacing="4x">
  <SearchInput placeholder="Search" defaultValue="John Doe" />
  <SearchInput placeholder="Search" defaultValue="John Doe" disabled />
</Stack>
```

**Comment by cheton** [comment]
Hi @derekhawker 

Thanks for highlighting this issue. The `SearchInput` component was an early implmentation with missing updates. For now, a better solution to it is to use `InputControl` and `InputAdornment` to compose a `SearchInput`.

I will take note of this.

**Comment by cheton** [comment]
Dark Mode
https://www.figma.com/file/bHr2zAshr0D5ROp8vCVPFR/%F0%9F%92%BC-Tonic---Dark-Mode?node-id=110%3A9

Light Mode
https://www.figma.com/file/62S1DnH4Pqy1MxJQCcLXUA/Tonic---Light-Mode?node-id=141%3A1
