### ISSUE TITLE
Link components don't have focus indicators

### ISSUE THREAD

**Issue by Esh-D** [cheton/styled-ui#623]
Hello, there is a small issue with the link component. When a user uses the keyboard to navigate a webpage, the link components don't have focus indicators to indicate to the user that they are hovering on a specific link. It makes it more difficult for keyboard-navigating users to navigate a webpage, since it can cause them to loose track of where they are on that webpage.

**Comment by cheton** [comment]
Related to #334 

I will create a PR to fix this legacy issue.
