### ISSUE TITLE
Alerts no longer show icon when `severity` prop is set

### ISSUE THREAD

**Issue by derekhawker** [cheton/styled-ui#625]
Hi, I was looking at the v1 page for Alerts, and noticed we aren't showing any icons for Alerts where we have passed a `severity` prop. I thought maybe it was a new behaviour because of the additional `icon` prop but the description for Icon says `severity` is used as a fallback icon. Looks like the conditional for displaying an AlertIcon is missing an `?? severity` or something ([ref](https://github.com/trendmicro-frontend/tonic-ui/blob/master/packages/react/src/alert/Alert.js#L53))

Screenshot of the current v1 page.
![image](https://user-images.githubusercontent.com/1403641/191843680-58f8031e-04f6-4d62-a6b8-00e9248d1ef6.png)
https://trendmicro-frontend.github.io/tonic-ui/react/latest/components/alert

Link to V0 for reference
https://trendmicro-frontend.github.io/tonic-ui/react/0.27.3/alert

**Comment by cheton** [comment]
It's a regression bug in v1, both `ToastIcon` and `AlertIcon` were affected.

**Comment by cheton** [comment]
Fixed in [v1.5.1](https://github.com/trendmicro-frontend/tonic-ui/releases/tag/%40tonic-ui%2Freact%401.5.1)

**Comment by derekhawker** [comment]
Thanks for the quick fix :)
