### ISSUE TITLE
Could Button variant use color defined in theme token?

### ISSUE THREAD

**Issue by JIM-CHEN** [cheton/styled-ui#661]
The [variant color](https://github.com/trendmicro-frontend/tonic-ui/blob/master/packages/react/src/button/styles.js#L397) of button is not from theme not allowed to use custom color.  Primary variant can use blue only.

How about use theme token to setup variant style by extending the [color style](https://trendmicro-frontend.github.io/tonic-ui/react/latest/components/color-style)? If that's reasonable for you, i can make a proposal.

**Comment by JIM-CHEN** [comment]
Or like radio/check box use variantColor? it's simpler

**Comment by cheton** [comment]
Hi @JIM-CHEN 

We're planning to introduce a new method for color customization and will be discontinuing the use of the `variantColor` prop as it creates an unnecessary dependency on theme tokens.

As a workaround, I recommend using the `styled` function to override existing styles, as shown in the example below:

```js
import styled from '@emotion/styled'
import { Button } from '@tonic-ui/react';

const CustomButton = styled(Button)`
  &:hover {
    // Add your desired hover styles here
  }
  &:active {
    // Add your desired active styles here
  }
  &:focus {
    // Add your desired focus styles here
  }
`;

export default CustomButton;
```

Reference: https://emotion.sh/docs/styled

Let me know if you have any further questions.
