### ISSUE TITLE
Popover do not support "PopperProps={{ usePortal: true }}"

### ISSUE THREAD

**Issue by TrendAlan** [cheton/styled-ui#671]
Tooltip support PopperProps={{ usePortal: true }} to show tooltip in portal mode.
But Popover missed this prop in [Popover.js](https://github.com/trendmicro-frontend/tonic-ui/blob/master/packages/react/src/popover/Popover.js#L12-#L32), though [PopoverContent.js](https://github.com/trendmicro-frontend/tonic-ui/blob/master/packages/react/src/popover/PopoverContent.js#L35) has this prop.
@cheton @light049

**Comment by cheton** [comment]
`Tooltip` is a composite component that uses `Popper` component to display a tooltip. It utilizes the `PopperProps` prop, similar to `PopoverContent`, in its `TooltipContent`.

```jsx
<TooltipContext.Provider value={context}>
  <TooltipTrigger
    shouldWrapChildren={shouldWrapChildren}
  >
    {children}
  </TooltipTrigger>
  <TooltipContent
    PopperComponent={PopperComponent}
    PopperProps={PopperProps}
    PopperArrowComponent={PopperArrowComponent}
    PopperArrowProps={PopperArrowProps}
    TransitionComponent={TransitionComponent}
    TransitionProps={TransitionProps}
    {...rest}
  >
    {label}
  </TooltipContent>
</TooltipContext.Provider>
```

Passing `PopperProps` via context is an option, but keeping the current approach makes it clear which components are being altered by these props.

**Comment by TrendAlan** [comment]
Got it now, `PopperProps `is used in `PopoverContent`, not in `Popover`.

Thank you
