### ISSUE TITLE
Tabs should be focusable by pressing space/enter while focused on TabButton

### ISSUE THREAD

**Issue by derekhawker** [cheton/styled-ui#690]
Seems like it would be a nice improvement so that we can navigate from just a keyboard. Currently we need to click on the tab with the mouse in order to change the tab.

And a question: While I was pressing tab, after the final TabButton, I noticed that the TabPanel is focusable. Is that intentional? It feels a bit odd because the TabPanel is a layout component and not necessarily interactive. 

<img width="619" alt="image" src="https://user-images.githubusercontent.com/1403641/219099698-3bd71d96-3194-42d7-808c-27ea7e57f559.png">

**Comment by cheton** [comment]
Related to https://github.com/trendmicro-frontend/tonic-ui/issues/668

**Comment by cheton** [comment]
@derekhawker It will be resolved in PR #694
