### ISSUE TITLE
Difficult to override font-family in Text And TextLabel

### ISSUE THREAD

**Issue by derekhawker** [cheton/styled-ui#727]
Is there a recommended way to set font family on a parent component so that is applied to all its child components? I was trying to set fontFamily on Stack and noticed that it wasn't applied to Text and TextLabel components. It might affect others, but those two were the only ones I noticed. I tried a couple variations like adding !important, using `style`/`css` props on the Stack component, and adding a \<Global\> block. The only solution I found that worked was to add `fontFamily` to each individual Text and TextLabel. Like so:

```
<Text fontFamily="cursive">Some text</Text>
```

I wasn't really happy with this solutions since it's easy to forget to add in one place which will create visual inconsistencies. It would be much better if we could set in a single place.

Here's some code to reproduce this and a screenshot I took while running it on [the docs for TextLabel](https://trendmicro-frontend.github.io/tonic-ui/react/latest/components/textlabel). To make it more obvious, I changed the fontFamily to 'cursive'

```
<Stack fontFamily="cursive">
    <TextLabel>Label text:</TextLabel>
    <Input value="Input component"/>
    <Text>Text component</Text>
    <Box>Box component</Box>
</Stack>
```

**Screenshot**

![image](https://user-images.githubusercontent.com/1403641/227337650-cd0d68fc-ed7d-440c-95be-65ab9f0979ca.png)

**Comment by cheton** [comment]
```js
const useTextStyle = ({ size }) => {
  const { fontSizes, lineHeights } = useTheme();

  return {
    display: 'block',
    fontFamily: 'base',
    fontSize: fontSizes?.[size],
    lineHeight: lineHeights?.[size],
  };
};
```

I agree that the `fontFamily` should not be applied by default to the `Text` component. Instead, only the standard set of font weights and sizes are necessary.

As a result, I will create a pull request to remove this style from the `Text` component, which will also affect the `TextLabel` componnet.

**Comment by cheton** [comment]
Updated in [1.15.1](https://github.com/trendmicro-frontend/tonic-ui/releases/tag/%40tonic-ui%2Freact%401.15.1)
