### ISSUE TITLE
Input cursor position changes to end in SearchInput when controlled usage

### ISSUE THREAD

**Issue by light049** [cheton/styled-ui#797]
Could be reproduced at [Keyword search](https://trendmicro-frontend.github.io/tonic-ui/react/latest/components/search-input#keyword-search) section in demo site.

1. Input some text
2. Change input cursor to the start position of input
3. Input text
4. The cursor would move to end of input when 1st character is typed

**Comment by cheton** [comment]
Related issues:
* https://stackoverflow.com/questions/46000544/react-controlled-input-cursor-jumps
* https://github.com/facebook/react/issues/18404#issuecomment-607539211
  ![image](https://github.com/trendmicro-frontend/tonic-ui/assets/447801/d17a31a7-88b9-4dbd-a4fd-da0518a7a962)

Proposed solutions include:
1. Do not alter the input value
2. Preserve and restore the cursor position, as shown in the example: https://codesandbox.io/s/boring-dirac-utq82?file=/src/App.tsx

**Comment by light049** [comment]
> 2. Preserve and restore the cursor position, as shown in the example: https://codesandbox.io/s/boring-dirac-utq82?file=/src/App.tsx

In the codesandbox, I could not reproduce the issue after removing code about 'selection'

<kbd><img width="1164" alt="image" src="https://github.com/trendmicro-frontend/tonic-ui/assets/1054905/d88e3a53-6b54-465f-af6a-0c813765d249"></kbd>

**Comment by cheton** [comment]
Reference:
https://egghead.io/lessons/react-preserve-cursor-position-when-filtering-out-characters-from-a-react-input

**Comment by cheton** [comment]
> > 2. Preserve and restore the cursor position, as shown in the example: https://codesandbox.io/s/boring-dirac-utq82?file=/src/App.tsx
> 
> In the codesandbox, I could not reproduce the issue after removing code about 'selection'

You have to press `Space` key to make string replacement work in this CodeSandbox example.

**Comment by light049** [comment]
But in this issue, there has no value modification in SearchInput, and it still has this behavior.
So, it might be separated into 2 parts to resolve:
- fix SearchInput for input cursor jumping to end
- enhance to help keep cursor position in input
