### ISSUE TITLE
Should UseToastManager methods be safe to use in useEffect?

### ISSUE THREAD

**Issue by derekhawker** [cheton/styled-ui#801]
Hi, 

I was trying to trigger toast methods inside a useEffect and got some eslint warnings because it wanted `toast` or `notify` to be added to the dependency array. But those references change anytime we create a new toast so adding to the dependency array triggers an infinite number of toasts to display. 

Was a little surprised by this as I though they would behave more like useState setters. I was curious... do you think it would be more ergonomic if these hook methods had immutable references? 

**How to trigger:**
Add the follow code snippet to [useToastManager demo](https://trendmicro-frontend.github.io/tonic-ui/react/latest/components/toast-manager/useToastManager) after handleClickOpenToast method

```
  const {notify} = toast;
  
  React.useEffect(()=>{
    handleClickOpenToast()
  },[notify])
```  

![image](https://github.com/trendmicro-frontend/tonic-ui/assets/1403641/24195595-187a-4161-821e-eb6bde2d797a)

**Comment by cheton** [comment]
The methods passed to the context lack the `useCallback` hook for function memoization, leading to unnecessary re-renders:

```js
// https://github.com/trendmicro-frontend/tonic-ui/blob/master/packages/react/src/toast/ToastManager.js#L225-L234
const context = getMemoizedState({
    // Methods
    close,
    closeAll,
    find,
    findIndex,
    notify,
    update,

    // Properties
    placement: placementProp,

    // State
    state,
    setState,
});
```

I think this issue can be resolved by using the `useCallback` Hook for those methods in `ToastManager`. Moreover, I'll check whether it is necessary to update the `useToastManager` Hook.

**Comment by cheton** [comment]
@derekhawker 

Could you help review the PR https://github.com/trendmicro-frontend/tonic-ui/pull/802? It should solve the issue you pointed out.
