### ISSUE TITLE
Idea: Scrollbar component supports scrolling to position

### ISSUE THREAD

**Issue by derekhawker** [cheton/styled-ui#807]
I think it could be useful for the Scrollbar component to support a way to set its position. I was running into a need for this recently while working on a Table that could be hidden from view.  The problem we're having is that when we make the Table visible again, it has lost the original scroll position so the user doesn't see the rows that were previously visible. This could also be useful in a Menu/dropdown with a large amount of options. We could save the scroll position whenver we select an option and tell Scrollbar to go to that position again upon opening. Being able to manually scroll Scrollbar is pretty much required in the case of Menu because MenuList is removed from DOM when Menu is closed.

It's technically possible to do this now, but it feels a bit brittle/hacky. You need to add a ref to Scrollbar and on that ref set `scrollTop` on its first child. I modified one of the codesandbox examples to show:

https://codesandbox.io/s/elated-dew-qvg8ky?file=/src/components/Dropdown.js
```
   useEffect(() => {
      setTimeout(() => {
        if (isOpen && refScrollbar.current) {
          refScrollbar.current.children[0].scrollTop = openScrollTop.current;
        }
      });
    }, [isOpen]);
```

I guess one of my concerns about doing this is we probably don't want to add a prop for position on Scrollbar. Scrolling needs to feel smooth and the last thing we want to do is call setState and re-render 60/sec during scrolling

**Comment by cheton** [comment]
Hi @derekhawker,

I created a PR #809 to address this issue. You can try the new enhancement in the codesandbox link:
https://codesandbox.io/s/reverent-dew-z47lm4?file=/src/app.js

**Comment by derekhawker** [comment]
@cheton, Oh... I never thought about using ref in a controlled component like that. That's a really nice solution for the performannce concerns I had. Thanks, this gives me all kind of ideas for things I might of used debounce for.
