### ISSUE TITLE
Should open prop to ToastContainer when using ToastManager

### ISSUE THREAD

**Issue by JIM-CHEN** [cheton/styled-ui#811]
The current Toast list align was start from 0 for example placement: 'top'. If we want the whole Toast list start from y 50, we need to add prop to ToastContainer. It's impossible to just add padding-bottom to Toasts.

https://github.com/trendmicro-frontend/tonic-ui/blob/master/packages/react/src/toast/ToastManager.js#L253

**Comment by cheton** [comment]
@JIM-CHEN It will be supported in https://github.com/trendmicro-frontend/tonic-ui/pull/814

**Comment by cheton** [comment]
Released [@tonic-ui/react@1.29.0](https://github.com/trendmicro-frontend/tonic-ui/releases/tag/%40tonic-ui%2Freact%401.29.0)

**Comment by JIM-CHEN** [comment]
@cheton 

Thank you for the quickly feature release. This PR already meet our requirement.


We found there's a defect on animation

1. When you have 3 toast on the screen
2. close the second toast
3. You will see the second toast run its animation
4. The third is going down but not smoothly

https://github.com/trendmicro-frontend/tonic-ui/assets/2099861/8272c7d2-3624-49b7-bb35-55071d60d64f

**Comment by cheton** [comment]
@JIM-CHEN

This issue was introduced from the outer margin. To address this:

1. Remove the space between toasts from the `TransitionProps`:

  ```jsx
  <ToastManager
    TransitionProps={{
      sx: {
        '[data-toast-placement^="top"] > &:first-of-type': {
          mt: '4x', // the space to the top edge of the screen
        },
        '[data-toast-placement^="bottom"] > &:last-of-type': {
          mb: '4x', // the space to the bottom edge of the screen
        },
        '[data-toast-placement$="left"] > &': {
          ml: '4x', // the space to the left edge of the screen
        },
        '[data-toast-placement$="right"] > &': {
          mr: '4x', // the space to the right edge of the screen
        },
      },
    }}
  >
  ```

2. In your toast layout, specify a bottom or top padding (e.g. `2x` or `8px`):

```jsx
const render = ({ onClose, placement }) => {
  const isTop = placement.includes('top');
  const toastSpacingKey = isTop ? 'pb' : 'pt';
  const styleProps = {
    [toastSpacingKey]: '2x', // 8px
    width: 320,
  };

  return (
    <Box sx={styleProps}>
      <Toast isClosable onClose={onClose}>
        <Text>This is a toast notification</Text>
      </Toast>
    </Box>
  );
};
```

I will update the document in a new PR for the updates.

**Comment by JIM-CHEN** [comment]
Much appreciated!!
