### ISSUE TITLE
[readme] Update README to v2

### ISSUE THREAD

**Issue by trend-albert-shala** [cheton/styled-ui#866]
Hi @cheton,
Small change need to update the read me for v2 changes
> Latest version (v1) => https://trendmicro-frontend.github.io/tonic-ui/

**Comment by cheton** [comment]
Hi @trend-albert-shala 

I completely forgot the README.md file. Thank you for pointing out the issue.

**Comment by cheton** [comment]
Updated in c26ad9b4902a4b533512e92016883f00a80e1bad
