### ISSUE TITLE
OverflowTooltip misalignment with popup menu items in Tonic UI V2

### ISSUE THREAD

**Issue by tinaClin** [cheton/styled-ui#893]
## Issue
When using @tonic-ui/react v2.0.1 in OverflowTooltip with a popup menu item, the tooltip position is not as expected.

### v1.27.0
![Screenshot2024_07_17_152639](https://github.com/user-attachments/assets/5d78705e-7ccb-4fe5-9d11-5d54bee28a0e)

### v2.0.1
![Screenshot2024_07_17_152852](https://github.com/user-attachments/assets/3c8ca70e-ccf0-41ad-a322-40fa1e078e61)

**Comment by cheton** [comment]
The distance calculation should consider the placement (top or bottom).

https://github.com/user-attachments/assets/b6ea4018-d204-471e-be76-b6dda60bd193
