### ISSUE TITLE
Bullet is missing when set as="li" for Text component in @tonic-ui/react v2.0.0

### ISSUE THREAD

**Issue by trend-alan-bie** [cheton/styled-ui#898]
Issue
-----
When using `Text` component as `li` in @tonic-ui/react v2.0.0, the list item's bullet will disappear.

V1
-----
<img width="748" alt="image" src="https://github.com/user-attachments/assets/efc281d1-2e2d-4677-ad63-40be2638a1d4">

V2
-----
<img width="725" alt="image (1)" src="https://github.com/user-attachments/assets/3e1e3a08-dd48-4bb1-9107-af31aafbb2dc">

**Comment by cheton** [comment]
Resolved in PR #899 by @trend-alan-bie
